spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: user
    password: pass

tibco:
  ems:
    server:
      url: tcp://localhost:7222
    credentials:
      username: yourUsername
      password: yourPassword
    queue:
      name: testQueue
